#
# Simple development makefile
#

#
# add more flags here,
# but don't remove the "+="
#
CFLAGS += -D_GNU_SOURCE -O2 -g -Wall -lm #-Wsign-compare -Wfloat-equal -Wformat-security #-Werror
CPPFLAGS += 
LDFLAGS += 


all: game

clean:
	-rm -f game

install:

rebuild:
	make clean
	make

.PHONY: all install clean rebuild

# end of development makefile
